POST http://localhost:8080/events/2/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0Nzk2MTM4LCJ1c2VyX2lkIjoyfQ.Q0NltOzsxUTopMzpN9sfPwTkmUPTZo-q-GhN2hl_3jk